import React, { useEffect, useState } from "react";

export default function ScenarioQuiz({ open, context, onClose }) {
  const [questions, setQuestions] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [source, setSource] = useState(null);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    async function load() {
      setBusy(true);
      setError(null);
      setSubmitted(false);
      setAnswers({});
      setQuestions(null);
      try {
        const response = await fetch("/api/mentor/quiz", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ context }),
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        if (cancelled) return;
        setQuestions(data.questions || []);
        setSource(data.source || "fallback");
      } catch (e) {
        if (!cancelled) setError(e.message);
      } finally {
        if (!cancelled) setBusy(false);
      }
    }
    load();
    return () => { cancelled = true; };
  }, [open, context?.summary?.sustainabilityScore, context?.summary?.debtToGdp2056]);

  if (!open) return null;

  const total = questions?.length || 0;
  const correctCount = !submitted
    ? 0
    : (questions || []).reduce((acc, q, i) => acc + (answers[i] === q.correctIndex ? 1 : 0), 0);

  return (
    <div className="tutorial-overlay" role="dialog" aria-label="Scenario quiz">
      <div className="quiz-card">
        <div className="quiz-header">
          <div>
            <span className="eyebrow"><span className="pip"></span>Atlas · Capstone quiz</span>
            <h2 className="display">Test what you just ran</h2>
            <p className="muted" style={{ margin: "6px 0 0", maxWidth: 540 }}>
              Five questions drawn from your actual scenario. Don't peek — answer first, then read the explanation.
              {source === "llm" ? " Generated by Atlas." : ""}
            </p>
          </div>
          <button className="btn ghost" onClick={onClose}>Close</button>
        </div>

        {busy && <p className="muted" style={{ padding: "30px 0" }}>Building your quiz…</p>}

        {error && (
          <div className="quiz-error">
            Couldn't reach the mentor: {error}
            <button className="btn" style={{ marginTop: 10 }} onClick={onClose}>Close</button>
          </div>
        )}

        {!busy && !error && questions && (
          <>
            <div className="quiz-questions">
              {questions.map((q, idx) => {
                const choice = answers[idx];
                const isAnswered = choice !== undefined;
                const isCorrect = submitted && choice === q.correctIndex;
                const isWrong = submitted && isAnswered && choice !== q.correctIndex;
                return (
                  <div key={idx} className={`quiz-q ${submitted ? "submitted" : ""}`}>
                    <div className="quiz-q-num">Question {idx + 1} of {total}</div>
                    <div className="quiz-q-body">{q.question}</div>
                    <div className="quiz-choices">
                      {q.choices.map((choiceText, cIdx) => {
                        const selected = choice === cIdx;
                        const correctMark = submitted && cIdx === q.correctIndex;
                        const wrongMark = submitted && selected && cIdx !== q.correctIndex;
                        return (
                          <button
                            key={cIdx}
                            type="button"
                            className={`quiz-choice ${selected ? "selected" : ""} ${correctMark ? "correct" : ""} ${wrongMark ? "wrong" : ""}`}
                            onClick={() => !submitted && setAnswers((prev) => ({ ...prev, [idx]: cIdx }))}
                            disabled={submitted}
                          >
                            <span className="quiz-choice-letter">{String.fromCharCode(65 + cIdx)}</span>
                            <span className="quiz-choice-text">{choiceText}</span>
                          </button>
                        );
                      })}
                    </div>
                    {submitted && (
                      <div className={`quiz-feedback ${isCorrect ? "ok" : "no"}`}>
                        <strong>{isCorrect ? "Correct" : isWrong ? "Not quite" : "Skipped"}</strong> · {q.explanation}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            <div className="quiz-footer">
              {!submitted ? (
                <button
                  className="btn"
                  onClick={() => setSubmitted(true)}
                  disabled={Object.keys(answers).length === 0}
                >
                  Submit answers
                </button>
              ) : (
                <div className="quiz-score">
                  <strong className="num">{correctCount} / {total}</strong>
                  <span className="muted">
                    {correctCount === total ? "Full marks. Defend your package."
                     : correctCount >= total - 1 ? "Strong run. One thing to revisit."
                     : correctCount >= total / 2 ? "Solid — re-read the explanations and run a new scenario."
                     : "Tough quiz. Go back to step 5 and read the scenario story, then try again."}
                  </span>
                  <button className="btn ghost" onClick={onClose}>Done</button>
                </div>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
